//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrandBlueResortandSpa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomBooking
    {
        public int roomBookId { get; set; }
        public string roomtype { get; set; }
        public System.DateTime checkindate { get; set; }
        public System.DateTime checkoutdate { get; set; }
        public string secretcode { get; set; }
    }
}
